### ISSUE TITLE
prevent infinite CIs (a conjecture)

### ISSUE THREAD

**Issue by benthestatistician** [josherrickson/pbph#6]
To estimate the SE of $\hat\eta$ we evaluate $B(\lambda)^{-1}$ at $\tilde{\lambda} = (\hat{\beta}_c, \tilde{\tau}_0, \eta_0)$, with no restriction placed on the restricted estimator $\tilde{\tau}_0$ of $\tau$.  I conjecture that $\tilde{\tau}_0$ were constrained to fall in an interval $I$, then the CI would cease to be infinite, provided only that the interval were finite and pre-determined. 

In practice one will have estimated $\tau$ and figured a confidence interval for it before one gets around to doing anything with $\eta$.  If one wants to report a 95% CI for $\eta$, then one might start by retrieving the previously determined 99% CI for $\tau$.  One then sets $I$ to that interval, in the process "spending" 1% of one's 5% testing budget for hypotheses about $\eta$. In order to wind up with a 95% CI for $\eta$, one would test each $H: \eta = \eta_0$ at level .04, not .05. If the conjecture is correct, one never gets an infinite CI.

**Comment by benthestatistician** [comment]
@josherrickson, you might think about whether you could come up with any easy ways of testing this conjecture without breaking your stride on other aspects of the diss.  Also, happy to discuss.

**Comment by josherrickson** [comment]
This conjecture was tested during the dissertation writing process and found to not hold up. It was implemented in the `bound_tau` branch.
